### PR TITLE
Hysteresis - inspired by Peishi's plots

### PR DESCRIPTION
**Pull request by bpbond**
Screen Shot 2020-08-27 at 9 51 46 PM

Screen Shot 2020-08-27 at 9 51 41 PM

### CODE REVIEW

**Comment by bpbond** [comment]
Use a diverging color gradient (so daylight hours are lighter-colored than nighttime hours) and show months.
x

**Comment by stephpenn1** [comment]
Super cool! So, taller circle = larger value range and wider circle = larger temp range?

**Comment by bpbond** [comment]
Right. And as the circle changes color, that's clock time (hour).

**Comment by bpbond** [comment]
The label positioning isn't great, but I defer to the expert (you) on that :)

**Pull request merged**
